### ISSUE TITLE
Shorter access to entity instance attributes

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/entity-system#125]
### Problem

Accessing the entity attribute values is currently very verbose.

### Goal

Make access to entity attributes shorter and more intuitive.

### Tasks

- [ ] Add bracket operator `[]` in `EntityInstance`
- [ ] Add template `get<DataType::?>()` in `EntityAttributeInstance`
- [ ] Add template `get<DataType::?>(attr_name)` in `EntityInstance`

### Test cases

```c++
// v1a: This is how it works now
EntityAttributeInstancePtr attr1 =  entity_instance->get_attribute_instance(name).value();
bool v1a = std::get<DataType::BOOL>(attr1->value.Value());
spdlog::info("v1a (145 chars) {}", v1a);

// v1b: As one liner
bool v1b = std::get<DataType::BOOL>(entity_instance->get_attribute_instance(name).value()->value.Value());
spdlog::info("v1b (106 chars) {}", v1b);

// v2a: shared_ptr (*) and bracket operator []
bool v2a = std::get<DataType::BOOL>((*entity_instance)[name]->value.Value());
spdlog::info("v2a (77 chars) {}", v2a);

// v3a: like v1a with shared_ptr (*), bracket operator []
EntityAttributeInstancePtr attr2 = (*entity_instance)[name];
bool v3a = attr2->get<DataType::BOOL>();
spdlog::info("v3a (101 chars) {}", v3a);

// v3b: like v1b with get<> on the attribute
bool v3b = entity_instance->get_attribute_instance(name).value()->get<DataType::BOOL>();
spdlog::info("v3b (88 chars) {}", v3b);

// v3c: like v2a and get<> on the attribute
bool v3c = (*entity_instance)[name]->get<DataType::BOOL>();
spdlog::info("v3c (59 chars) {}", v3c);

// v4: get<>(attr_name) on entity instance
bool v4a = entity_instance->get<DataType::BOOL>(name);
spdlog::info("v4a (54 chars) {}", v4a);

```
